ServerName localhost
Listen 443
LoadModule ssl_module modules/mod_ssl.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
ProxyRequests Off

<VirtualHost _default_:443>
  SSLEngine on
  SSLCertificateFile /run/secrets/web_cert.pem
  SSLCertificateKeyFile /run/secrets/web_key.pem

  SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
  SSLCipherSuite HIGH:!aNULL:!MD5
  SSLHonorCipherOrder on

  DocumentRoot "/usr/local/apache2/htdocs"
  <Directory "/usr/local/apache2/htdocs">
    Require all granted
  </Directory>

  ProxyPass        /api/ http://api/api/
  ProxyPassReverse /api/ http://api/api/
</VirtualHost>